language: python

services:
  - postgresql
  - mysql

python:
  - 3.6

before_install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements-dev.txt
  - pip install --upgrade pytest

install: pip install -ve .

script: py.test -vv --cov-report term-missing:skip-covered --cov=microhttp microhttp

after_success: if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then travis_retry coveralls
  ; fi

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "hloeOrvz1VpWOx97vbGDTkKDxf3okJ4gIdpLenH3lH1NfyjFJ74jDkZZ1Y5exjb23OO4E621QrOnBFSbUVSMwHE1H7gVxDS9FLRInMn0nE2wTxv6cBKO5/ZtgQD3rxNdVhik594RAxutVwLxGMoHZGH0CJH6zo1QfX2K79SCefL7pNX8dQeau2RLZzxRmFLVV3t7GkC+n1aiOzu8QhbT6VDxZpgbqhq/ai7LshhQh6esCuTHkd5Ehp3eB2Stt4zmQcy/lk7rBLr6eZ0xchn6In88UHuwEwumycILmTekrRVbNSpHyBjgSklzJYPb2G3NRRzkCCj3YML7XKo0FRuKb9CXyRS7EktrBOgh0JOiDvHcT/5CVvp/HE5pFIVZX5gZJbE4bK1RB8zjgLsAipYU4E7N1ho8ZmESITCJdHaO116q3iQn5uGHpWmnq6B3DGZv8d2eun/oat2xxwfr6vebhj3rgiDAZXULHsdvswn8prizwPZT1eKcBWkpmygIyyeYkAdRnS72RWB3O7DWObZJZ3qU9LmgjY+GWUyzqt2F3meOg/uwr3mKwwfyv6ZFU2qFyOrrKJ529Wc7Hf9nKX98WThoE7jzkzlJig9jyamMJXQ99ecBwveifPvwTrJbH/o6OB0u5qGZgL3NcvYQhl8MPBvqumUk25x+VVYGcurv/nY="
  on:
    tags: true
    distributions: sdist bdist_wheel
  skip-cleanup: true
  skip_existing: true

